[[vanity]]
import_path = "m4o.io/pbf"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/p2y"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/gslog"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/aws-s3"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/bugs"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/joincontext"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/GoRx"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/GoRxGenerics"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/quaternions"
vcs = "git"
vcs_path = "https://github.com/maguro"

[[vanity]]
import_path = "m4o.io/yoko-is-lovely"
vcs = "git"
vcs_path = "https://github.com/maguro"
